import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import ClientTheme from "@/components/ClientTheme/ClientTheme";
import "./globals.css";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Koob",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientTheme>
      <html lang="en">
          <body className={nunitoSans.className}>{children}</body>
      </html>
    </ClientTheme>
  );
}
